app = "deserve-monitor"
primary_region = "fra"

[http_service]
internal_port = 1881
auto_stop_machines = "off"
min_machines_running = 1
force_https = true
processes = [ "app" ]

[[vm]]
size = "shared-cpu-2x"
cpu_kind = "shared"
cpus = 2
memory = 512